Project
Winifred
2025-07-11
Set working directory and loading the data
pd <- read.csv("personality_dataset.csv", stringsAsFactors = F)
Checking the structure of the data
str(pd)
## 'data.frame':    2900 obs. of  8 variables:
##  $ Time_spent_Alone         : num  4 9 9 0 3 1 4 2 10 0 ...
##  $ Stage_fear               : chr  "No" "Yes" "Yes" "No" ...
##  $ Social_event_attendance  : num  4 0 1 6 9 7 9 8 1 8 ...
##  $ Going_outside            : num  6 0 2 7 4 5 NA 4 3 6 ...
##  $ Drained_after_socializing: chr  "No" "Yes" "Yes" "No" ...
##  $ Friends_circle_size      : num  13 0 5 14 8 6 7 7 0 13 ...
##  $ Post_frequency           : num  5 3 2 8 5 6 7 8 3 8 ...
##  $ Personality              : chr  "Extrovert" "Introvert" "Introvert" "Extrovert" ...
Checking missing values and duplicates
any(is.na(pd)) #Checking for missing values generally
## [1] TRUE
sapply(pd, function(x) sum(is.na(x))) #Checking for missing values column by column
##          Time_spent_Alone                Stage_fear   Social_event_attendance 
##                        63                         0                        62 
##             Going_outside Drained_after_socializing       Friends_circle_size 
##                        66                         0                        77 
##            Post_frequency               Personality 
##                        65                         0
anyDuplicated(pd) #Checking for duplicate
## [1] 48
Removing duplicates
duplicate <- pd[duplicated(pd),]
#pd <- pd[!duplicated(pd),]
pd <- unique(pd)
anyDuplicated(pd)
## [1] 0
str(pd)
## 'data.frame':    2512 obs. of  8 variables:
##  $ Time_spent_Alone         : num  4 9 9 0 3 1 4 2 10 0 ...
##  $ Stage_fear               : chr  "No" "Yes" "Yes" "No" ...
##  $ Social_event_attendance  : num  4 0 1 6 9 7 9 8 1 8 ...
##  $ Going_outside            : num  6 0 2 7 4 5 NA 4 3 6 ...
##  $ Drained_after_socializing: chr  "No" "Yes" "Yes" "No" ...
##  $ Friends_circle_size      : num  13 0 5 14 8 6 7 7 0 13 ...
##  $ Post_frequency           : num  5 3 2 8 5 6 7 8 3 8 ...
##  $ Personality              : chr  "Extrovert" "Introvert" "Introvert" "Extrovert" ...
Replacing Missing values
numeric_col <- names(pd[sapply(pd, is.numeric)])
pd[numeric_col]<- data.frame(lapply(pd[numeric_col], function(x) ifelse(is.na(x), round(median(x, na.rm = T),0), x)))

factor_col <- names(pd[sapply(pd, is.character)])
pd[factor_col]<- data.frame(lapply(pd[factor_col], function(x) ifelse(is.na(x) | x=="", names(which.max(table(x))), x)))

pd[factor_col] <- data.frame(lapply(pd[factor_col], function(x) as.factor(x)))

str(pd)
## 'data.frame':    2512 obs. of  8 variables:
##  $ Time_spent_Alone         : num  4 9 9 0 3 1 4 2 10 0 ...
##  $ Stage_fear               : Factor w/ 2 levels "No","Yes": 1 2 2 1 1 1 1 1 2 1 ...
##  $ Social_event_attendance  : num  4 0 1 6 9 7 9 8 1 8 ...
##  $ Going_outside            : num  6 0 2 7 4 5 3 4 3 6 ...
##  $ Drained_after_socializing: Factor w/ 2 levels "No","Yes": 1 2 2 1 1 1 1 1 2 1 ...
##  $ Friends_circle_size      : num  13 0 5 14 8 6 7 7 0 13 ...
##  $ Post_frequency           : num  5 3 2 8 5 6 7 8 3 8 ...
##  $ Personality              : Factor w/ 2 levels "Extrovert","Introvert": 1 2 2 1 1 1 1 1 2 1 ...
sapply(pd, function(x) sum(is.na(x)))
##          Time_spent_Alone                Stage_fear   Social_event_attendance 
##                         0                         0                         0 
##             Going_outside Drained_after_socializing       Friends_circle_size 
##                         0                         0                         0 
##            Post_frequency               Personality 
##                         0                         0
Summarizing non numeric columns
non_numeric <- pd[sapply(pd, is.factor)]
lapply(non_numeric, function(x) table(x))
## $Stage_fear
## x
##   No  Yes 
## 1421 1091 
## 
## $Drained_after_socializing
## x
##   No  Yes 
## 1423 1089 
## 
## $Personality
## x
## Extrovert Introvert 
##      1417      1095
Summarizing numeric columns
numeric <- pd[sapply(pd, is.numeric)]
lapply(numeric, function(x) summary(x))
## $Time_spent_Alone
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    0.00    1.00    3.00    4.18    7.00   11.00 
## 
## $Social_event_attendance
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.000   2.000   4.000   4.214   7.000  10.000 
## 
## $Going_outside
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.000   1.000   3.000   3.199   5.000   7.000 
## 
## $Friends_circle_size
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.000   3.000   6.000   6.589  10.000  15.000 
## 
## $Post_frequency
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.000   1.000   3.000   3.811   6.000  10.000
Vituals of non numeric columns
non_numeric <- pd[sapply(pd, is.factor)]
for(col in names(non_numeric)){
  barplot(table(pd[col]), col = c("orange","darkgreen"), xlab = col, ylab = "Frequency", main = paste("Bar Chart Plot of ", col))
}
   
non_numeric <- pd[sapply(pd, is.factor)]
for(col in names(non_numeric)){
  pie(table(pd[col]), col = c("blue","green"),  main = paste("Pie Chart Plot of ", col))
}
   
Boxplot and Histogram of numeric Variables
for(col in names(numeric)){
  boxplot(pd[col], col="orange", main = paste("Box plot of ", col))
}
     
for(col in names(numeric)){
  hist(pd[[col]], col="red", main = paste("Distribution of ", col))
}
     
numeric_col <- names(pd[sapply(pd, is.numeric)])
cols <- numeric_col
for (i in cols){
  boxplot(pd[[i]] ~pd$Personality, main = paste("Box Plot of", i, "against Personality"), xlab = "Personality", ylab = i)
}
     
Correlations of Numeric variables
factor_cold <- pd[, sapply(pd, is.factor)]
y <- factor_cold[-3]
lapply(y, function(x) {
  table(pd$Personality,x)
})
## $Stage_fear
##            x
##               No  Yes
##   Extrovert 1312  105
##   Introvert  109  986
## 
## $Drained_after_socializing
##            x
##               No  Yes
##   Extrovert 1312  105
##   Introvert  111  984
Divide the data into Train and test using 80 to 20 percent
set.seed(123)
train_sample <- sample(nrow(pd), 80/100*nrow(pd))
train_pd <- pd[train_sample,]
test_pd <- pd[-train_sample,]
str(train_pd)
## 'data.frame':    2009 obs. of  8 variables:
##  $ Time_spent_Alone         : num  8 11 7 5 1 4 10 5 3 3 ...
##  $ Stage_fear               : Factor w/ 2 levels "No","Yes": 2 2 2 2 1 2 2 2 1 1 ...
##  $ Social_event_attendance  : num  2 1 1 2 6 1 2 0 5 7 ...
##  $ Going_outside            : num  1 3 0 2 7 1 1 2 6 4 ...
##  $ Drained_after_socializing: Factor w/ 2 levels "No","Yes": 2 2 2 2 1 2 2 2 1 1 ...
##  $ Friends_circle_size      : num  1 2 2 5 13 4 4 3 14 12 ...
##  $ Post_frequency           : num  1 0 1 2 10 1 2 2 3 3 ...
##  $ Personality              : Factor w/ 2 levels "Extrovert","Introvert": 2 2 2 2 1 2 2 1 1 1 ...
Fitting Regression Model
logr_model <- glm(Personality~., data = train_pd, family = "binomial")
summary(logr_model)
## 
## Call:
## glm(formula = Personality ~ ., family = "binomial", data = train_pd)
## 
## Coefficients:
##                               Estimate Std. Error z value Pr(>|z|)    
## (Intercept)                  -2.402213   0.539616  -4.452 8.52e-06 ***
## Time_spent_Alone             -0.049283   0.041848  -1.178   0.2389    
## Stage_fearYes                 2.511553   0.367330   6.837 8.07e-12 ***
## Social_event_attendance      -0.044097   0.050587  -0.872   0.3834    
## Going_outside                -0.001082   0.070168  -0.015   0.9877    
## Drained_after_socializingYes  2.605689   0.369468   7.053 1.76e-12 ***
## Friends_circle_size           0.067214   0.033462   2.009   0.0446 *  
## Post_frequency               -0.077810   0.050609  -1.537   0.1242    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 2758.4  on 2008  degrees of freedom
## Residual deviance: 1137.7  on 2001  degrees of freedom
## AIC: 1153.7
## 
## Number of Fisher Scoring iterations: 5
Personality_Lr <- predict(logr_model, test_pd, type = "response")

Pred_Personality_Lr <- ifelse(Personality_Lr< 0.5, "Extrovert", "Introvert")
library(Metrics)
Accuracy_Lr<- accuracy(test_pd$Personality,Pred_Personality_Lr)
Accuracy_Lr
## [1] 0.9184891
library(class)
normalize <- function(x){
  (x-min(x))/(max(x)-min(x))
}
pdk <- pd[-c(2,5,8)]
pdkn <- data.frame(lapply(pdk, function(x) normalize(x)))
train_knn <- pdkn[train_sample,]
label_train <- train_pd$Personality
test_knn <- pdkn[-train_sample,]
label_test <- test_pd$Personality
Results <- data.frame(K = numeric(), Accuracy = numeric() )
for(k in 1:20){
Personality_knn <- knn(train=train_knn, test=test_knn, cl=label_train, k=k)
library(Metrics)
Accuracy_knn <- accuracy(label_test,Personality_knn)
Results <- rbind(Results,data.frame(K=k, Accuracy=Accuracy_knn))
}
Results
##     K  Accuracy
## 1   1 0.8667992
## 2   2 0.8966203
## 3   3 0.9324056
## 4   4 0.9304175
## 5   5 0.9383698
## 6   6 0.9443340
## 7   7 0.9423459
## 8   8 0.9343936
## 9   9 0.9383698
## 10 10 0.9403579
## 11 11 0.9383698
## 12 12 0.9403579
## 13 13 0.9403579
## 14 14 0.9403579
## 15 15 0.9383698
## 16 16 0.9383698
## 17 17 0.9403579
## 18 18 0.9383698
## 19 19 0.9403579
## 20 20 0.9403579
Personality_knn <- knn(train=train_knn, test=test_knn, cl=label_train, k=6)
Accuracy_knn <- accuracy(label_test,Personality_knn)
Accuracy_knn
## [1] 0.9383698
library(gmodels)
CrossTable(label_test,Personality_knn,prop.chisq=FALSE)
## 
##  
##    Cell Contents
## |-------------------------|
## |                       N |
## |           N / Row Total |
## |           N / Col Total |
## |         N / Table Total |
## |-------------------------|
## 
##  
## Total Observations in Table:  503 
## 
##  
##              | Personality_knn 
##   label_test | Extrovert | Introvert | Row Total | 
## -------------|-----------|-----------|-----------|
##    Extrovert |       277 |        20 |       297 | 
##              |     0.933 |     0.067 |     0.590 | 
##              |     0.962 |     0.093 |           | 
##              |     0.551 |     0.040 |           | 
## -------------|-----------|-----------|-----------|
##    Introvert |        11 |       195 |       206 | 
##              |     0.053 |     0.947 |     0.410 | 
##              |     0.038 |     0.907 |           | 
##              |     0.022 |     0.388 |           | 
## -------------|-----------|-----------|-----------|
## Column Total |       288 |       215 |       503 | 
##              |     0.573 |     0.427 |           | 
## -------------|-----------|-----------|-----------|
## 
## 
if(Accuracy_Lr > Accuracy_knn) cat("The best model is Logistic Regression with accuracy of", round(Accuracy_Lr,2)) else cat("The best model is K-Nearest Neighbour with accuracy of", round(Accuracy_knn,2))
## The best model is K-Nearest Neighbour with accuracy of 0.94
